version: "3.3"
services:
  # Built using the local source
  psip-local:
    build: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080 # DEFAULT VALUE
      BASEURL: /api # DEFAULT VALUE

  # Pulled from hub.docker.com container registry with 'latest' tag
  psip-remote:
    image: technicallyjoe/psip:latest
    ports:
      - 8081:8080
    environment:
      PORT: 8080 # DEFAULT VALUE
      BASEURL: /api # DEFAULT VALUE
